### ISSUE TITLE
Compilation error with PlatformIO and LoRa32u4

### ISSUE THREAD

**Issue by Nihlus** [sudomesh/LoRaLayer2#21]
I'm currently trying to compile the library as a part of an experiment on a LoRa32u4 board, but I'm running into trouble with the use of a `printf` where it is seemingly not supported. The problem in question shows up here,

https://github.com/sudomesh/LoRaLayer2/blob/349341f41b7ea1173bbef44a31aabcd008397e0d/src/Layer1_LoRa.cpp#L169

, and wrapping it in a `#ifdef LL2_DEBUG` like the others around it resolves the problem.

**Comment by paidforby** [comment]
Yes, that should definitely be wrapped in an `#ifdef LL2_DEBUG`. I can make the change in master, unless you feel a strong desire to make a pull request. Thanks for pointing this out.
